apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  template:
    spec:
      containers:
        - name: hello-job
          image: busybox
          command: ["echo", "Hello from Kubernetes Job"]
      restartPolicy: Never
