apiVersion: batch/v1
kind: Job
metadata:
  name: multi-job
spec:
  completions: 3
  template:
    spec:
      containers:
        - name: multi-pod
          image: busybox
          command: ["echo", "Task completed"]
      restartPolicy: Never