apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
spec:
  completions: 10
  parallelism: 5
  template:
    spec:
      containers:
        - name: parallel-pod
          image: busybox
          command: ["echo", "Parallel task running"]
      restartPolicy: Never