apiVersion: batch/v1
kind: Job
metadata:
  name: auto-cleanup-job
spec:
  ttlSecondsAfterFinished: 60 # delete job after 60 seconds
  template:
    spec:
      containers:
        - name: auto-cleanup-pod
          image: busybox
          command: ["echo", "Cleanup..."]
      restartPolicy: Never