apiVersion: batch/v1
kind: CronJob
metadata:
  name: scheduled-cronjob
spec:
  schedule: "*/1 * * * *" # every 1 minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scheduled-pod
              image: busybox
              command: ["date"]
          restartPolicy: OnFailure
