apiVersion: batch/v1
kind: CronJob
metadata:
  name: python-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: python-pod
              image: python:3-alpine
              command: ["python"]
              args: ["-c", "print('Hello from Kubernetes CronJob')"]
          restartPolicy: Never
