apiVersion: v1
kind: Pod
metadata:
  name: readiness-command
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      readinessProbe:
        exec:
          command: ["pg_isready"]
        initialDelaySeconds: 5
        periodSeconds: 10
      env:
        - name: POSTGRES_PASSWORD
          value: secret
