apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcp
spec:
  containers:
    - name: mysql
      image: mysql
      ports:
        - containerPort: 3306
      livenessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 10
        periodSeconds: 5
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
