apiVersion: v1
kind: Pod
metadata:
  name: liveness-command
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      livenessProbe:
        exec:
          command: ["pg_isready"]
        initialDelaySeconds: 10
        periodSeconds: 5
      env:
        - name: POSTGRES_PASSWORD
          value: secret
