apiVersion: v1
kind: Pod
metadata:
  name: env-pod
  labels:
    app: env-pod
spec:
  containers:
    - name: alpine-app
      image: alpine
      env:
      - name: APP_ENV
        value: "production"
      command: ["sleep", "3600"]
