apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
  labels:
    app: readiness-pod
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      readinessProbe:
        exec:
          command: ["cat", "/tmp/ready"]
        initialDelaySeconds: 5
        periodSeconds: 5
