apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-01
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/k8s-data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvc-pod
  template:
    metadata:
      labels:
        app: pvc-pod
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sh", "-c", "echo 'Hello from PVC' > /data/hello.txt; sleep 3600"]
          volumeMounts:
            - name: pvc-volume
              mountPath: "/data"
      volumes:
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: pvc-01
