apiVersion: v1
kind: Pod
metadata:
  name: restricted-capabilities-pod
spec:
  containers:
    - name: my-container
      image: nginx
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]   # Allows network admin actions
          drop: ["ALL"]        # Drops all other capabilities
