apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev-environment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      name: nginx-app
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
      
