apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sa-pod-deployment
  template:
    metadata:
      labels:
        app: sa-pod-deployment
    spec:
      serviceAccountName: my-service-account
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "3600"]
