apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx-rs
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
