apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: python:3.10-alpine
          ports:
            - containerPort: 80
          command: ["python", "-m", "http.server", "80"]

---

apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    app: python-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30200