apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: python:3.10-alpine
          ports:
            - containerPort: 80
          command: ["python", "-m", "http.server", "8080"]

---

apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    app: python-app
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-app
  template:
    metadata:
      labels:
        app: busybox-app
    spec:
      containers:
        - name: busybox-app
          image: busybox:latest
          command: ["/bin/sh"]
          args: ["-c", "while true; do wget -q -O- http://python-service:8080; sleep 1; done"]
